// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skjedicyojhdhcovygjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNramVkaWN5b2poZGhjb3Z5Z2pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NzI4NTQsImV4cCI6MjA2OTI0ODg1NH0.FzdXXyGukuxq6f6GECxvHStNEIw-tHXmGhsek0khCaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});